name: Keep workflows alive

# Controls when the action will run. 
on:
  schedule:
    - cron:  '0 0 * * 6'
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
        with:
          workflow_files: "test-conda-anaconda-basiccpp.yml, test-conda-anaconda.yml, test-conda-miniconda-basiccpp.yml, test-conda-miniconda.yml, test-conda-miniforge-basiccpp.yml, test-conda-miniforge.yml, test-mamba-miniforge-basiccpp.yml, test-mamba-miniforge.yml, test-precompiled-tar.yml, test-snap-embedded.yml, test-snap-rootrc.yml, test-snap-wrappers.yml, test-snap.yml"
          time_elapsed: 40
