name: Test ROOT from precompiled .tar.gz

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 0 1 * *'
  workflow_dispatch:

jobs:
  install-and-test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5

      - name: Install ROOT dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libtbb12

      - name: Install dependencies
        run: |
          sudo apt-get -y install build-essential dpkg-dev cmake g++ gcc binutils libx11-dev libxpm-dev libxft-dev libxext-dev python3 libssl-dev

      - name: Install ROOT
        run: |
          TARBALL=root_v6.34.08.Linux-ubuntu24.04-x86_64-gcc13.3.tar.gz
          wget --no-verbose https://root.cern/download/${TARBALL}
          tar -xzvf ${TARBALL}

      - name: Run ROOT
        run: |
          source root/bin/thisroot.sh
          root --version

      - name: Test compiling
        run: |
          source root/bin/thisroot.sh
          make

      - name: Run
        run: |
          source root/bin/thisroot.sh
          ./analysis
          ls -la
