name: Test ROOT from Snap store, run inside Snap

# Controls when the action will run. 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  install-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get -y install build-essential

      - name: Install ROOT
        run: |
          sudo snap install root-framework

      - name: Run ROOT
        run: |
          root --version

      - name: Test compiling
        run: |
          echo "make" | snap run --shell root-framework

      - name: Run
        run: |
          echo "./analysis" | snap run --shell root-framework
          ls -la
