name: Test ROOT via Conda using Miniforge

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 0 1 * *'
  workflow_dispatch:

jobs:
  install-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo apt-get -y install build-essential

      - name: Setup Miniforge
        run: |
          wget "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
          bash Miniforge3-$(uname)-$(uname -m).sh -b -p ~/miniforge

      - name: Create ROOT virtualenv
        run: |
          source ~/miniforge/etc/profile.d/conda.sh
          conda create -n my_root_env root root_base

      - name: Upgrade conda itself
        run: |
          source ~/miniforge/etc/profile.d/conda.sh
          conda activate my_root_env
          conda update -n base -c defaults conda

      - name: Upgrade all from conda-forge channel
        run: |
          source ~/miniforge/etc/profile.d/conda.sh
          conda activate my_root_env
          conda upgrade --all

      - name: Run ROOT
        run: |
          source ~/miniforge/etc/profile.d/conda.sh
          conda activate my_root_env
          root --version

      - name: Test compiling
        run: |
          source ~/miniforge/etc/profile.d/conda.sh
          conda activate my_root_env
          make

      - name: Run
        run: |
          source ~/miniforge/etc/profile.d/conda.sh
          conda activate my_root_env
          ./analysis
          ls -la
