name: Test ROOT via Conda using Miniconda

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 0 1 * *'
  workflow_dispatch:

jobs:
  install-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get -y install build-essential

      - name: Setup Miniconda
        run: |
          wget -nv http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p ~/miniconda
          echo 'channel_priority: strict' > ~/.condarc
      
      - name: Create ROOT virtualenv
        run: |
          source ~/miniconda/etc/profile.d/conda.sh
          conda create -n my_root_env root -c conda-forge

      - name: Upgrade conda itself
        run: |
          source ~/miniconda/etc/profile.d/conda.sh
          conda activate my_root_env
          conda update -n base -c defaults conda

      - name: Upgrade all from conda-forge channel
        run: |
          source ~/miniconda/etc/profile.d/conda.sh
          conda activate my_root_env
          conda upgrade -c conda-forge --all

      - name: Run ROOT
        run: |
          source ~/miniconda/etc/profile.d/conda.sh
          conda activate my_root_env
          root --version

      - name: Test compiling
        run: |
          source ~/miniconda/etc/profile.d/conda.sh
          conda activate my_root_env
          make

      - name: Run
        run: |
          source ~/miniconda/etc/profile.d/conda.sh
          conda activate my_root_env
          ./analysis
          ls -la
